#!/bin/bash

owner=tmc
dockersite="docker.tmcdx.com:5000"
#if [ -z $1 ] 
#then
#    echo 'dckbuild [owner (default=${owner})] # for $dockersite'
#    exit
#fi

pathset=$(echo $PWD | tr "/" "\n")
for x in $pathset
do
  currentpath=$x
done
LG='\033[1;30m'
H='\033[1;33m'
T='\033[0;36m'
NC='\033[0m' # No Color

dimage="${owner}/${currentpath}"
dckreg="${dockersite}/${dimage}:latest"

echo -e "${T}Building ${H}$dimage${NC}:latest"
echo -e "${LG}-----------------------------------------------------------------------${NC}"
docker build -t $dimage:latest . 

