#!/bin/bash

if [ -z "$3" ]
then
	echo "${0} [SITEDIR] [BOXDIR] [web:job,live,yellow] [folder1,folder2,folder3,...] (#,..,... define to skip dckbuild for sub images)"
	echo "Example: "
    echo "  dcknow playsite playbox job modules/typ,themes/contrib,sites 0,3"
    exit
fi

PATHSET=$(echo $PWD | tr "/" "\n")
for X in $PATHSET
do
    CURRENTPATH=$X
done

SITEDIR=$1
BOXDIR=$2
WEB=$3
FOLDERS=$4;

IFS=',' 
read -ra MODULES <<<"$4"

IFS=','
read -ra SKIPBUILT <<<"$5"

SITEDIR=${PWD}/${SITEDIR}/www/$WEB/web
BOXDIR=${BOXDIR}

G='\033[1;30m'
H='\033[1;33m'
T='\033[0;36m'
M='\033[1;35m'
N='\033[0m' # No Color

PARTNO=0
SRC=${1}/www
DEST=${BOXDIR}/${CURRENTPATH}-${PARTNO}/root
mkdir -p ${DEST}

echo -e "${G}${T}Working with ${H}${FOLDERS}${T}......"
echo " "
echo -e "${G}=== ${T}Syncing ${H}${SRC}${T} to ${H}${DEST}${N}"
mkdir -p $DEST

echo -e "${M}"
rsync --exclude '.*' -a --delete $SRC $DEST 
echo -e "${NC}"


for PART in "${MODULES[@]}"
do
    ((PARTNO=PARTNO+1))
    SRC=${BOXDIR}/${CURRENTPATH}-0/root/www/${WEB}/web/${PART}/*
    DEST=${BOXDIR}/${CURRENTPATH}-${PARTNO}/root/www/${WEB}/web/${PART}
    echo " "
    echo -e "${G}=== ${T}Spliting ${H}${SRC}${T} to ${H}${DEST}${N}"
    mkdir -p $DEST
    echo -e "${M}"
    rsync --exclude '.*' --exclude 'hg-*' -av --delete $SRC $DEST 
    echo -e "${NC}"
    rm -rf $SRC
done



echo " "
echo -e "${T}Creating ${H}Dockerfile${T}......${N}"

echo "FROM busybox" > Dockerfile
echo "MAINTAINER vorapoap@teleinfomedia.co.th" >> Dockerfile
echo "ENV TIMEZONE Asia/Bangkok" >> Dockerfile
#echo "COPY --chown=48:48 drupal /root/www/drupal" >> Dockerfile

DCKHEADER=$(cat <<-END
FROM busybox
ENV TIMEZONE Asia/Bangkok
END
)


I=0
while [ $I -le $PARTNO ]
do
    DEST=/root/www
    SRC=playbox/${CURRENTPATH}-${I}/root/*
    DOCKERFILE=playbox/${CURRENTPATH}-${I}/Dockerfile
    DOCKERIGNORE=playbox/${CURRENTPATH}-${I}/.dockerignore

    echo "${DCKHEADER}" > $DOCKERFILE
    echo "COPY --chown=48:48 ${DEST} /root/www/" >> $DOCKERFILE

    echo "VOLUME /www" >> $DOCKERFILE
    echo "CMD cp -prf /root/www/* /www" >> $DOCKERFILE    
    echo ".*" > $DOCKERIGNORE
    echo "hg-*">> $DOCKERIGNORE
    ((I=I+1))
done

echo ""
echo -e "${T}Dockerbuild / Dockerpush ${H}dckbuild/dckpush${T}......${NC}"
I=0
while [ $I -le $PARTNO ]
do
    SRC=${PWD}/${BOXDIR}/${CURRENTPATH}-${I}
    echo -e "${G}===== ${H}${BOXDIR}/${CURRENTPATH}-${I}/Dockerfile${NC}"
    if [[ "${SKIPBUILT[*]}" =~ "${I}" ]]
    then
        echo -e "${G}===== ${T}SKIP Building/Pushing Dockerfile${NC}"
        echo ""
    else
        ( cd ${SRC}; cat Dockerfile )
        echo ""
        ( cd ${SRC}; dckbuild; dckpush )
        echo ""
        echo ""
    fi

    ((I=I+1))
done

#DOCKERFILE=Dockerfile
#echo "FROM ${OWNER}/${CURRENTPATH}-${PARTNO}:latest AS A${PARTNO}" > $DOCKERFILE
#echo "COPY /root/* /root" >> $DOCKERFILE
#
#((I=PARTNO-1))
#while [ $I -ge 0 ]
#do
#    ((V=I+1))
#    echo "FROM ${OWNER}/${CURRENTPATH}-${I}:latest AS A${I}" >> $DOCKERFILE
#    echo "COPY --from A${V} /root/* /root" >> $DOCKERFILE
#    ((I=I-1))
#done
#echo "VOLUME /www" >> $DOCKERFILE
#echo "CMD cp -prf /root/www/* /www" >> $DOCKERFILE
#
#echo -e "${G}===== ${H}Dockerfile${N}"
#cat $DOCKERFILE
#echo ""
#dckbuild
echo ""
