#!/bin/bash

owner=tmc
dockersite="docker.tmcdx.com"
#if [ -z $1 ] 
#then
#    echo 'dckbuild [owner (default=${owner})] # for $dockersite'
#    exit
#fi

pathset=$(echo $PWD | tr "/" "\n")
for x in $pathset
do
  currentpath=$x
done
LG='\033[1;30m'
H='\033[1;33m'
T='\033[0;36m'
NC='\033[0m' # No Color

if [ ! -f version.txt ] 
then
  dversion=`date +%Y%m%d.1` 
  echo ${dversion} > version.txt
else
  ddate=`date +%Y%m%d`
  awk -F. '{printf("'${ddate}'.%d",$2+1)}' OFS=. version.txt  > tmp && mv tmp version.txt
  dversion=$(cat "version.txt")
fi
dimage="${owner}/${currentpath}"
dckreg="${dockersite}/${dimage}:${dversion}"
dckreg2="${dockersite}/${dimage}:latest"

echo -e "${T}Logging to docker registry ${H}$dockersite${NC}"
echo -e "${LG}-----------------------------------------------------------------------${NC}"
docker login $dockersite
echo "Done"
echo

echo -e "${T}Tagging ${H}$dimage${NC} for ${H}$dckreg${NC}" and ${H}$dckreg2${NC}
echo -e "${LG}-----------------------------------------------------------------------${NC}"
docker tag $dimage $dckreg
docker tag $dimage $dckreg2
echo "Done"
echo 

echo -e "${T}Pushing ${H}$dimage:latest${NC}${T} to ${H}$dckreg${NC}" adn ${H}$dckreg2${NC}
echo -e "${LG}-----------------------------------------------------------------------${NC}"
docker push $dckreg2
docker push $dckreg
echo 
