#!/bin/bash

owner=vorapoap
#if [ -z $1 ] 
#then
#    echo 'dckbuild [owner (default=${owner})] # for $dockersite'
#    exit
#fi

pathset=$(echo $PWD | tr "/" "\n")
for x in $pathset
do
  currentpath=$x
done
LG='\033[1;30m'
H='\033[1;33m'
T='\033[0;36m'
NC='\033[0m' # No Color

dimage="${owner}/${currentpath}:latest"

echo -e "${T}Stop and remove any previous docker image ${H}test${NC}"
echo -e "${LG}-----------------------------------------------------------------------${NC}"
docker stop test
docker container rm test
echo "Done"
echo

echo -e "${T}Testing ${H}$dimage:latest${NC}${T} as ${H}test${NC}"
echo -e "${LG}-----------------------------------------------------------------------${NC}"
docker run -P --detach --name test $dimage &
sleep 1 
echo

echo -e "${T}Docker Process${NC}"
echo -e "${LG}-----------------------------------------------------------------------${NC}"
docker ps
echo 
