#!/bin/bash


if [ -z $1 ]
then
	echo "${0} [cert]"
    exit
fi


LG='\033[1;30m'
H='\033[1;33m'
T='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${T}Certificate ${H}$1${NC}"
kuebctl describe certificate $1 -nlandingpage
certreq=$(kuebctl describe certificate $1 -nlandingpage|tail -n 1|awk 'NF>1{print $NF}'|sed -e 's/"//g')
echo ""
if [ "${certreq}" == "successfully" ] 
then
    exit
fi
if [ "${certreq}" == "<none>" ] || [ "${certreq}" == "" ]
then 
    exit
fi

echo -e "${T}CertificateRequest ${H}${certreq}${NC}"
kuebctl describe certificaterequest ${certreq} -nlandingpage
order=$(kuebctl describe certificaterequest $certreq -nlandingpage|tail -n 1|awk 'NF>1{print $NF}'|sed -e 's/landingpage\///g')
echo ""

echo -e "${T}Order ${H}${order}${NC}"
kuebctl describe order ${order} -nlandingpage
challenge=$(kuebctl describe order ${order} -nlandingpage|tail -n 1|awk '{print $8}'|sed -e 's/"//g')
echo ""

echo -e "${T}Challenge ${H}${challenge}${NC}"
kuebctl describe challenge ${challenge} -nlandingpage
