#!/bin/sh

LG='\033[1;30m'
H='\033[1;33m'
T='\033[0;36m'
NC='\033[0m' # No Color

if [ -z $2 ]
   then
       echo "$0 [prod or dev] [command .....]"
       exit
   fi


export CONSOLE_NAMESPACE=$1
#"${1}"

BN="$(basename -- $2)"
DIR="$(dirname -- $2)"
cd $DIR

echo -e "${T}Working Path${NC} is changed to ${H}${DIR}${NC}"
echo -e "${T}CONSOLE_NAMESPACE${NC} is set to ${H}$1${NC}"
echo -e "${T}Running... ${H}${BN} ${3} ${4} ${5} ${6} ${7} ${8} ${9}${NC}"


./${BN} ${3} ${4} ${5} ${6} ${7} ${8} ${9}
