#!/bin/bash

#'.$namespace.' '.$destsvc.' '.$certname.' '.$domain. ' '.$custid;
if [ -z $5 ] 
then
	echo "${0} [namespace]  [domain] [custid]"
	exit
fi

CERT=$3
DOMAIN=$4
#INGRESS=${4//\./-}
#kubectl delete ingressroute ${INGRESS}
DESTSERVICE=$2
DATE="$(date +%Y%m%d)-$(uuidgen)"
NS=$1
CUSTID=$5

OUT=/devop/k8s/typ/ingress/landingpage/${CUSTID}.yml

LG='\033[1;30m'
H='\033[1;33m'
T='\033[0;36m'
NC='\033[0m' # No Color


echo -e "${T}Removing IngressRoute ${DOMAIN}-${CUSTID}...${NC}"
kubectl delete ingressroute ${DOMAIN}-${CUSTID} -n${NS}

