#!/bin/bash

#'.$namespace.' '.$destsvc.' '.$certname.' '.$domain. ' '.$custid;
if [ -z $1 ] 
then
	echo "${0} [custid]"
	exit
fi

CUSTID=$1

OUT=/devop/k8s/typ/ingress/landingpage/${CUSTID}.yml

LG='\033[1;30m'
H='\033[1;33m'
T='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${T}Clean up IngressRoute by removing file ${H}${OUT}${NC}..."
rm ${OUT}
