#!/bin/bash

#'.$namespace.' '.$destsvc.' '.$certname.' '.$domain. ' '.$custid;
if [ -z $5 ] 
then
	echo "${0} [namespace] [dest] [cert] [domain] [custid]"
	exit
fi

CERT=$3
DOMAIN=$4
#INGRESS=${4//\./-}
#kubectl delete ingressroute ${INGRESS}
DESTSERVICE=$2
DATE="$(date +%Y%m%d)-$(uuidgen)"
NS=$1
CUSTID=$5

OUT=/devop/k8s/typ/ingress/landingpage/${CUSTID}.yml

LG='\033[1;30m'
H='\033[1;33m'
T='\033[0;36m'
NC='\033[0m' # No Color

cat << EOT >> ${OUT}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ${DOMAIN}-${CUSTID}
  namespace: ${NS}
  labels:
    customerid: '${CUSTID}'
    date: ${DATE}
    domain: ${DOMAIN}
spec:
  tls:
    domain:
    - ${DOMAIN}
    secretName: ${CERT}
    namespace: ${NS}
  entryPoints:
    - websecure
    - web
  routes:
  - kind: Rule
    match: Host(\`${DOMAIN}\`)
    priority: 1000
    services:
    - name: ${DESTSERVICE}
      namespace: prod
      port: 80
EOT

echo -e "${T}Creating IngressRoute ${H}${DOMAIN}-${CUSTID}${T}...${NC}"
kubectl apply -f $OUT #--namespace=${NS}

