#!/bin/bash

#'.$namespace.' '.$destsvc.' '.$certname.' '.$domain. ' '.$custid;
if [ -z $1 ] 
then
	echo "${0} [domain]"
	exit
fi

DOMAIN=$1
#INGRESS=${4//\./-}
#kubectl delete ingressroute ${INGRESS}
NS=landingpage


LG='\033[1;30m'
H='\033[1;33m'
T='\033[0;36m'
NC='\033[0m' # No Color

DELROUTE=`kubectl get ingressroute -nlandingpage |grep ${DOMAIN}|head -n 1|awk -F " " ' { print $1 }' `

echo -e "${T}Removing IngressRoute ${DELROUTE}...${NC}"
kubectl delete ingressroute ${DELROUTE} -n${NS}
echo ""
echo -e "${T}Removing Cert ${DOMAIN}-cert...${NC}"
kubectl delete cert ${DOMAIN}-cert -n${NS}
echo ""

