#!/bin/bash

if [ -z $1 ] 
then
  echo 'Usage: kubconfigmap [dir] [namespace (default=dev)]'
  exit

else
  dir=$1
  pathset=$(echo $1 | tr "/" "\n")
  for x in $pathset
  do
    currentpath=$x
  done
  fs=${currentpath}
fi

if [ ! -f $dir ]
then
    if [ ! -d $dir ] 
    then
      echo "$0: File or directory '${dir}' not found."
      exit
    fi
fi

LG='\033[1;30m'
H='\033[1;33m'
T='\033[0;36m'
NC='\033[0m' # No Color


if [ -z $2 ]
then
  ns=dev
else
  ns=$2
fi

if [ -d ${dir}/${ns} ] 
then
    dir="${dir}/${ns}" 
    echo -e "${T}Found ${H}${dir}${T} inside...."
fi


echo -e "${T}Setting configmap ${H}$fs${T} in namespace ${H}$ns${T} from files in ${H}$dir${NC}"
echo -e "${LG}-----------------------------------------------------------------------${NC}"
kubectl create configmap $fs --from-file=$dir -n$ns
kubectl create configmap $fs --from-file=$dir -o yaml --dry-run=client -n$ns| kubectl replace -f -
echo
#echo -e "${T}Result${NC}"
#echo -e "${LG}-----------------------------------------------------------------------${NC}"
#kubectl describe configmap $1
#echo

