#!/bin/bash

if [ -z $1 ] 
then
  echo 'Usage: kucert [dir] [namespace (default=dev)]'
  exit

else
  dir=$1
fi

if [ ! -f $dir ]
then
    if [ ! -d $dir ] 
    then
      echo "$0: File or directory '${dir}' not found."
      exit
    fi
fi


if [ -z $2 ]
then
  ns=dev
else
  ns=$2
fi
LG='\033[1;30m'
H='\033[1;33m'
T='\033[0;36m'
NC='\033[0m' # No Color


echo -e "${T}Setting cert ${H}$dir${T} in namespace ${H}$ns${T} from files in ${H}tls.crt ad tls.key${NC}"
echo -e "${LG}-----------------------------------------------------------------------${NC}"
kubectl delete secret $dir -n$ns
kubectl create secret tls $dir --key=$dir/tls.key --cert=$dir/tls.crt -n$ns
# | kubectl apply -n$ns -f -
echo
#kubectl get secret -n$ns
