#!/bin/bash

if [ -z $1 ]
then
    echo "$0 [ingressroutename] [namespace (default=dev)]"
fi

if [ -z $2 ]
then
    ns=dev
else
    ns=$2
fi

LG='\033[1;30m'
H='\033[1;33m'
T='\033[0;36m'
NC='\033[0m' # No Color



cd "/typ/ingress/${ns}"
if [ ! -f "${1}.yml" ]
then    
    echo "${1} doesn't exist."
    ls *.yml 
    exit
fi

echo -e "${T}Deleting ingressroute ${NC}${1}${T} from namespace ${H}${ns}${NC}"
echo -e "${G}------------------------------------------------------"
kubectl delete ingressroute ${1} -n$ns
echo ""

echo -e "${T}Creating ingressroute ${NC}${1}${T} from namespace ${H}${ns}${NC}"
echo -e "${G}------------------------------------------------------"
kubectl apply -f ${1}.yml -n$ns
echo ""
