#!/bin/bash

if [ -z $1 ] 
then 
  echo 'Usage: kubingress [filename (without .yml)] [namespace (default=dev)]'
  exit

else
  fs=${1//.yml/}

fi

if [ ! -f "$fs.yml" ]
then
    echo "$0: File '${fs}.yml' not found."
    exit
fi


if [ -z $2 ]
then
  ns=dev
else
  ns=$2
fi
LG='\033[1;30m'
H='\033[1;33m'
T='\033[0;36m'
NC='\033[0m' # No Color

#echo -e "${T}Deleting ingress ${H}$fs.yml${NC}${T} from Kubernetes Namespace ${H}$ns${NC} ${T}"
#echo -e "${LG}-----------------------------------------------------------------------${NC}"
#kubectl delete ingressroute -n$ns $fs
#echo "Done."

latest=`date +%Y%m%d-%H%M%S`
echo -e "${T}Applying ${H}$fs.yml${NC}${T} UPDATE=${H}$latest${T} to Kubernetes Namespace ${H}$ns${NC} ${T}"
echo -e "${LG}-----------------------------------------------------------------------${NC}"
sed 's/UPDATE/'$latest'/g' $fs.yml | kubectl apply -n$ns -f -
echo 
