#!/bin/bash
echo 'Usage: kububuild [namespace (default=dev)]'


  pathset=$(echo $PWD | tr "/" "\n")
  for x in $pathset
  do
    currentpath=$x
  done
  fs=${currentpath//.yml/}



if [ ! -f "$fs.yml" ]
then
    echo "$0: File '${fs}.yml' not found."
    exit
fi


if [ -z $1 ]
then
 ns=dev
else
 ns=$1
fi

echo -e "${J}Checking for ${fs}.${ns}.yml....${NC}"
if [ -f "${fs}.${ns}.yml" ]
then
    fs=${fs}.${ns}
    echo -e "Found file '${H}${fs}${T}' for namespace '${H}${ns}${T}'"
else
    echo -e "Notfound..."
fi




LG='\033[1;30m'
H='\033[1;33m'
T='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${T}Deleting ${H}$fs.yml${NC}${T} to Kubernetes Namespace ${H}$ns${NC}"
echo -e "${LG}-----------------------------------------------------------------------${NC}"
kubectl delete -f $fs.yml -n$ns
echo
echo -e "${T}Status${NC}"
echo -e "${LG}-----------------------------------------------------------------------${NC}"
kubectl get all -n$ns|grep $fs
echo 
