#!/bin/bash
if [ -z $1 ]
then
    echo "${0} [podname] [namespace (default=dev)] (silence)"
    exit
fi

if [ -z $2 ]
then
    NS=dev
else
    NS=$2
fi

G='\033[1;30m'
H='\033[1;33m'
T='\033[0;36m'
NC='\033[0m' # No Color


FPOD=$1

if [[ $3 != "silence" ]]
    then
        echo ""
        echo -e "${T}Pod Set${G}:   ${H}${FPOD}"
        echo -e "${T}Namespace${G}:  ${H}${NS}${NC}"
    fi

FINDPOD=`kubectl get pod -n${NS}|grep typ-${FPOD}|awk '{print $1}'`
for POD in $FINDPOD
do
    NODE=`kubectl describe pod ${POD} -n${NS} |grep Node:|sed 's/Node:\s*//g'|sed 's/\/.*//g'|head -n 1`
    PODID=`kubpodid ${NS} | grep ${POD} | awk -F" " '{print $2}'|head -n 1`

    if [[ $NODE = "" ]]
    then
        echo "Can't find Node for this Pod"
        exit
    fi

    if [[ $PODID = "" ]]
    then
        echo "Can't find Pod ID for this Pod"
        exit
    fi
    STORAGE=/var/lib/kubelet/pods/${PODID}/
    
    if [[ $3 != "silence" ]]
    then
        echo -e "${T}POD${G}:        ${H}${POD}${NC}"
        echo -e "${T}Node${G}:       ${H}${NODE}${NC}"
        echo -e "${T}Pod ID${G}:     ${H}${PODID}${NC}"    
        echo -e "${T}Storage${G}:    ${H}${STORAGE}${NC}"
        echo -e "${G}------------------------------------------------------------------------${NC}"
        echo ""
    else
        echo ${NODE}:$STORAGE
    fi

done
exit

#ssh ${NODE} find /var/lib/kubelet/pods/${PODID}

