#!/bin/bash

if [ -z $2 ]
then
   echo "$1 srcdb destdb"
fi


SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

if [ ! -f "${DIR}/_secrets/config.sh" ]
then
            echo "Database secret file _secrets/config.sh doesn't exist."
            exit
fi
source "${DIR}/_secrets/config.sh"

G='\033[1;30m'
H='\033[1;33m'
T='\033[0;36m'
N='\033[0m' # No Color

echo -e "${T}Cloning ${H}${1} ${T}to ${H}${2}...${N}"

mysqldump -u ${DBUSER} -p${DBPASS} -h proxysql-cluster --add-drop-table ${1} | mysql -u ${DBUSER} -p${DBPASS} -h proxysql-cluster ${2}
echo "Done"
