#!/bin/bash

if [ -z $1 ]
then
            echo " -p Check processlist in all percona/proxysql instances (percona=3 proxysql=5)"
            echo "-o Check proxysql-cluster latency & stat overview"
            echo "-c Check proxysql-cluster connection stats"
            echo "-s Check slow-query and digest logs from proxsql-cluster "
            echo "-v Check mysql server hostgroups"
            echo "-r Check proxysql query rules"
            exit
fi
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

if [ ! -f "${DIR}/_secrets/config.sh" ]
then
            echo "Database secret file _secrets/config.sh doesn't exist."
            exit
fi
source "${DIR}/_secrets/config.sh"

LG='\033[1;30m'
H='\033[1;33m'
T='\033[0;36m'
J='\033[0;35m'
NC='\033[0m' # No Color

sv=1

while getopts "pgrvocs" option; do
    case "${option}" in
        p)
            echo -e "${LG}===== ${T}PerconaXtraDB Server${LG} =====${NC}"
            mysqladmin -h percona1 -u ${DBUSER} -p${DBPASS} processlist|wc
            mysqladmin -h percona2 -u ${DBUSER} -p${DBPASS} processlist|wc
            mysqladmin -h percona3 -u ${DBUSER} -p${DBPASS} processlist|wc

            echo -e "${LG}===== ${T}ProxySQL Cluster${LG} =====${NC}"            
            mysqladmin -h k8sw1 -P 30006 -u ${DBUSER} -p${DBPASS} processlist|wc
            mysqladmin -h k8sw2 -P 30006 -u ${DBUSER} -p${DBPASS} processlist|wc
            mysqladmin -h k8sw3 -P 30006 -u ${DBUSER} -p${DBPASS} processlist|wc
            mysqladmin -h k8sw4 -P 30006 -u ${DBUSER} -p${DBPASS} processlist|wc
            mysqladmin -h k8sw5 -P 30006 -u ${DBUSER} -p${DBPASS} processlist|wc
        ;;
        g)
            echo -e "${LG}===== ${T}Galera Logs${LG} =====${NC}"
            mysql -u ${PROXYSQLADMIN}  -p${PROXYSQLADMINPASS} -h k8sw${sv} -P 30032 -e "select * from mysql_server_galera_log"
        ;;
        r)
            echo -e "${LG}===== ${T}Query Rules${LG} =====${NC}"
            #mysql -u ${PROXYSQLADMIN}  -p${PROXYSQLADMINPASS} -h k8sw${sv} -P 30032 -e "select match_pattern,multiplex,destination_hostgroup,re_modifiers,active from runtime_mysql_query_rules"
            mysql -u ${PROXYSQLADMIN}  -p${PROXYSQLADMINPASS} -h k8sw${sv} -P 30032 -e "SELECT hits, mysql_query_rules.rule_id,digest, match_digest, match_pattern, destination_hostgroup,re_modifiers,replace_pattern, cache_ttl, apply FROM mysql_query_rules NATURAL JOIN stats.stats_mysql_query_rules ORDER BY mysql_query_rules.rule_id;"
        ;;
        v)
            echo -e "${LG}===== ${T}MySQL Servers${LG} =====${NC}"            
            mysql -u ${PROXYSQLADMIN}  -p${PROXYSQLADMINPASS} -h k8sw${sv} -P 30032 -e "select hostgroup_id,hostname,status,port,max_connections,weight from runtime_mysql_servers"
            echo -e "${LG}===== ${T}Galera Hostgroups${LG} =====${NC}"
            mysql -u ${PROXYSQLADMIN}  -p${PROXYSQLADMINPASS} -h k8sw${sv} -P 30032 -e "select * from mysql_galera_hostgroups"        
        ;;        
        o)
            echo -e "${LG}===== ${T}Connection Pool${LG} =====${NC}"
            mysql -u ${PROXYSQLADMIN}  -p${PROXYSQLADMINPASS} -h k8sw${sv} -P 30032 -e "select * from stats_mysql_connection_pool"
            echo -e "${LG}===== ${T}Command Counter${LG} =====${NC}"
            mysql -u ${PROXYSQLADMIN}  -p${PROXYSQLADMINPASS} -h k8sw${sv} -P 30032 -e "SELECT * FROM stats_mysql_commands_counters WHERE Total_cnt"
        ;;
        c) 
            echo -e "${LG}===== ${T}Connection Stat${LG} =====${NC}"
            mysql -u ${PROXYSQLADMIN}  -p${PROXYSQLADMINPASS} -h k8sw${sv} -P 30032 -e "select * from stats.stats_mysql_global where variable_name like '%connect%';"  
            mysql -u ${PROXYSQLADMIN}  -p${PROXYSQLADMINPASS} -h k8sw${sv} -P 30032 -e "SELECT * FROM stats_mysql_global WHERE Variable_Name LIKE 'Query_Cache%';"
        ;;
        s)
            echo -e "${LG}===== ${T}Slow log ${LG}===== ${NC}"
            mysql -u ${PROXYSQLADMIN}  -p${PROXYSQLADMINPASS} -h k8sw${sv} -P 30032 -e "select count_star,sum_time,(sum_time/count_star)/1000 as average_time_ms,digest_text from stats_mysql_query_digest where count_star > 100 order by average_time_ms desc limit 10;"
            echo -e "${LG}===== ${T}Digest log ${LG}===== ${NC}"
            mysql -u ${PROXYSQLADMIN}  -p${PROXYSQLADMINPASS} -h k8sw${sv} -P 30032 -e "SELECT hostgroup hg, sum_time, count_star, digest, digest_text FROM stats_mysql_query_digest ORDER BY sum_time DESC limit 10;"
        ;;

esac
done
