#!/bin/bash
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

if [ ! -f "${DIR}/_secrets/config.sh" ]
then
            echo "Database secret file _secrets/config.sh doesn't exist."
            exit
fi
source "${DIR}/_secrets/config.sh"


ssh root@percona1 mysqladmin -u root -p${DBROOTPASS} processlist
ssh root@percona2 mysqladmin -u root -p${DBROOTPASS} processlist
ssh root@percona3 mysqladmin -u root -p${DBROOTPASS} processlist

