#!/bin/bash
if [ $0 != "-bash" ] || [ -z $1 ]  
then
   echo "Always run this command with '. $0 [target typ-xxxxx playsite]"
   exit
fi

LG='\033[1;30m'
H='\033[1;33m'
T='\033[0;36m'
NC='\033[0m' # No Color


cd /devop/docker-images/typ-$1/playsite/www
echo -e "${T}Changed to ${H}$PWD${LG}...${NC}"
echo ""
