#!/bin/bash
if [ -z ${1} ]
then
    echo "$0 [pod deployment name] (container|default=first container) (no|default=first) (...command....|default=sh)"
    exit
fi

if [ -z "${3}" ]
then
    NO=1
else
    NO=${3}
fi

if [ -z "${4}" ]
then
    COMMAND=/bin/sh
else
    COMMAND="${4}"
fi

PODNAME=$(kubectl get pod |grep $1|grep Running|head -n ${NO}|awk  '{ print $1 }'|tail -n 1)

if [ -z "${2}" ]
then
    #echo kubectl get pods ${PODNAME} -o jsonpath='{.spec.containers[*].name}'
    container=$(kubectl get pods ${PODNAME} -o jsonpath='{.spec.containers[*].name}')
else
    container=$2;
fi    

LG='\033[1;30m'
H='\033[1;33m'
T='\033[0;36m'
J='\033[0;35m'
NC='\033[0m' # No Color

echo -e "${T}Executing command in ${H}${PODNAME} ${T}pod # ${H}${NO} ${T}container ${H}${container}${NC}"
kubectl exec -it $PODNAME  -c ${container} -- ${COMMAND}
