#!/bin/bash
if [ -z $3 ] 
then
	echo "${0} [namespace] [domain] [custid]"
  exit
fi



DOMAIN=$2
DATE="$(date +%Y%m%d)-$(uuidgen)"
NS=$1
CUSTID=$3

OUTPUT=/devop/k8s/typ/secret/certs/${CUSTID}.yml

LG='\033[1;30m'
H='\033[1;33m'
T='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${T}Saving Cert file to ${H}$OUTPUT${T}...${NC}"
cat > ${OUTPUT} << EOT
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ${DOMAIN}-cert
  namespace: ${NS}
  labels:
    date: ${DATE}
    customerid: '${CUSTID}'
    domain: ${DOMAIN}
spec:
  dnsNames:
  - ${DOMAIN}
  commonName: ${DOMAIN}
  secretName: ${DOMAIN}-cert
  issuerRef:
    name: ${NS}-letsencrypt-prod
EOT
kubectl apply -f ${OUTPUT}


#kubectl -n $NS describe certificate "${DOMAIN}"

